-- Wygenerowane przez tools/make_manifest.lua - nie edytuj recznie
return {
  version = "1.3.1",
  files = {
    "install.lua",
    "update.lua",
    "smart/gui/menu.lua",
    "smart/lib/autocraft.lua",
    "smart/lib/auto.lua",
    "smart/lib/chatbot.lua",
    "smart/lib/config.lua",
    "smart/lib/devices.lua",
    "smart/lib/displays.lua",
    "smart/lib/gfx.lua",
    "smart/lib/history.lua",
    "smart/lib/mod.lua",
    "smart/lib/ollama.lua",
    "smart/lib/remote.lua",
    "smart/lib/sources.lua",
    "smart/lib/theme.lua",
    "smart/lib/ui.lua",
    "smart/lib/util.lua",
    "smart/main.lua",
    "smart/modules/alarms.lua",
    "smart/modules/autocraft.lua",
    "smart/modules/boiler.lua",
    "smart/modules/clock.lua",
    "smart/modules/control.lua",
    "smart/modules/create.lua",
    "smart/modules/energy.lua",
    "smart/modules/fission.lua",
    "smart/modules/flow.lua",
    "smart/modules/fusion.lua",
    "smart/modules/history.lua",
    "smart/modules/machines.lua",
    "smart/modules/menu.lua",
    "smart/modules/mesearch.lua",
    "smart/modules/overview.lua",
    "smart/modules/players.lua",
    "smart/modules/radiation.lua",
    "smart/modules/storage.lua",
    "smart/modules/tanks.lua",
    "smart/modules/turbine.lua",
    "smart/pocket.lua",
    "startup/smart.lua",
  },
  pocket = {
    "install.lua",
    "update.lua",
    "startup/smart.lua",
    "smart/lib/util.lua",
    "smart/lib/gfx.lua",
    "smart/lib/ui.lua",
    "smart/lib/theme.lua",
    "smart/pocket.lua",
  },
  changelog = {
    "Ollama: oryginalny blad CC + podpowiedz w menu i dzienniku",
    "Menu Czat i AI: wiersz 'Laczy z' i 'Blad CC'",
  },
}
